### ISSUE TITLE
How to prepare .h5 file for testing?

### ISSUE THREAD

**Issue by adaxidedakaonang** [yaozhong/URnano#1]
Thank you.

**Comment by yaozhong** [comment]
For nanopore, they use a similar format called "*.fast5". 
I think you can directly using .fast5 as the input for testing.

For example, you can find nanopore fast5 reads here
https://github.com/nanopore-wgs-consortium/NA12878/blob/master/Genome.md

**Comment by adaxidedakaonang** [comment]
I download the chiron train data and code is running correctly now. But there still has few questions for me. Firstly, what the meaning of cache file. Does it be validation file for training? Does this fast5 file includes the label and signal? Thanks~

**Comment by adaxidedakaonang** [comment]
Hi yaozhong, you seem forget to offer URnet.model.parameters.json. In the path: MODEL="./experiment/model/", you offer Unet rather than URnet. Can you offer me URnet model? Thanks~
In addition, you seem forget to offer Loss in your train instruction.

**Comment by yaozhong** [comment]
The cached file saves the processed data used for training/testing deep learning model.
Using the cached data, you can focus on deep learning module part.

Based on Chiron author’s description,
*.signal and *.label are generated from their fast5, you can check details in Teng’s paper.
We do not directly provide fast5, but only provide basecalling interface for fast5 raw data.

**Comment by yaozhong** [comment]
The basic hyper-parameters of U-net and UR-net are the same for comparison. 
The specific layers and according parameters in UR-net are fixed in the model module.
Therefore the basic configure are the same for both U-net and UR-net.

If you like to change UR-net specific layers and according parameters, you can revised the network structure defined in the models/model_unet.py
We will refine it in the next update. Thanks.

**Comment by adaxidedakaonang** [comment]
For .fast5 file, in your code, I found if there is no cached file, than you will generate it based on original data. 
For Unet model file, I changed its name to URnet and program worked fine. Thank you for answering my confusion!
