### ISSUE TITLE
Confused about training step in paper.

### ISSUE THREAD

**Issue by adaxidedakaonang** [yaozhong/URnano#2]
In section 2.2, you use D={X,Y} to train cnn model. I have a question, raw signal's length may longer than label. For example, signal data 12,30,10 has a correspond label A. So how do you make label has the same length as signal data when training network? Thank you.

**Comment by yaozhong** [comment]
Yes, the input and output of the UR-net have exactly the same length. 
The raw signal input is first split into non-overlapping vectors with the same length (e.g. 300).
For each element in the vector, we will assign a segment label for it and merge consecutive identical segment labels in a later stage.

**Comment by adaxidedakaonang** [comment]
For example, in a window there has three normalized elements:  -0.51, -0.28, -0.55, -0.57, -0.52. There only has one label A. So to keep the same length,one method is add A in each position :A_1, A_1, A_1, A_1, A_1. Another is add zero :0, 0, A_1, 0, 0. In train_urnet.py, line79, I see "could be padding with extra 0 in the end part." Could you tell me how do you keep the same length with signal? Thanks!
就是两个做法，第一个是 假如A在3335-3340之间，那么我给这一段的每个信号点对应的标签都是A。另一个做法不太合适但是也可以，就是A后面补0.这样。这两个是我的猜想。方便透露一下你们是如何对标签延拓的吗？谢谢了！

**Comment by yaozhong** [comment]
> On Oct 29, 2019, at 16:17, adaxidedakaonang <notifications@github.com> wrote:
> 
> For example, in a window there has three normalized elements: -0.51, -0.28, -0.55, -0.57, -0.52.
> There only has one label A. So to keep the same length,one method is add A in each position :A_1, A_1, A_1, A_1, A_1.

This is the correct understanding. 
After the prediction of UR-net, we will do post-processing that transform consecutive A_1, A_1, A_1,A_1, A_1 to A.



> Another is add zero :0, 0, A_1, 0, 0. In train_urnet.py, line79, I see "could be padding with extra 0 in the end part." Could you tell me how do you keep the same length with signal? Thanks!

No, we do not do it in this way and this seems not correct for real physical process.


Best,

Zhang

**Comment by adaxidedakaonang** [comment]
Thank you~
