### ISSUE TITLE
Confused about normalizing signal.

### ISSUE THREAD

**Issue by adaxidedakaonang** [yaozhong/URnano#3]
In your paper, you use  median shift and median abs deviation to normalize signal. However, in your code ,you use mean value and std value normalize signal. I try both methods and only mean operation has the same  waveform with your paper.  So actually don't you use normalize method proposed in your paper?

**Comment by yaozhong** [comment]
For standard  fast5 signals normalization, median shift and median abs deviation are commonly used to normalize raw signals. Here, we used Chiron's dataset, the signal files provided are already normalized. 
In the train deep learning models, we take additional step of standardizing the input signals with mean and std to stable the training process.

**Comment by adaxidedakaonang** [comment]
OK, thanks~
